module.exports = [
    "car",
    "car-gas",
    "car-insurance",
    "car-loan",
    "car-maintenance",
    "car-registration",
    "cash",
    "checks",
    "clothing",
    "clothing-chad",
    "clothing-juli",
    "education",
    "electronics",
    "entertainment",
    "gifts given",
    "groceries",
    "groceries-alcohol",
    "hobbies",
    "home",
    "home-hoa dues",
    "home-improvements",
    "home-maintenance",
    "home-merchandise",
    "home-mortgage",
    "home-yard",
    "life insurance",
    "medical",
    "medical-dental",
    "medical-equipment",
    "medical-prescriptions",
    "medical-services",
    "online services",
    "online services-hosting",
    "parking",
    "personal care",
    "pets",
    "postage and shipping",
    "professional",
    "restaurants",
    "restaurants-work lunch",
    "taxes",
    "taxes-federal",
    "taxes-georgia",
    "taxes-preparation",
    "transportation services",
    "travel",
    "travel-dining",
    "travel-lodging",
    "travel-merchandise",
    "travel-pet care",
    "travel-transportation",
    "utilities",
    "utilities-electricity",
    "utilities-gas",
    "utilities-internet",
    "utilities-security",
    "utilities-water",
    "utilities-wireless service",
    "work expense",
    "atm fee rebate",
    "deposits",
    "gifts received",
    "income services",
    "interest earned",
    "investment income",
    "medical reimbursements",
    "other income",
    "work income",
    "work income-bonus",
    "work income-salary",
    "work reimbursement",
    "credit card payments",
    "savings accounts",
    "transfers",
    "transfers-hsa",
    "transfers-annuity",
    "transfers-savings",
    "uncategorized"
]
