module.exports = {
    searches: [
        { search: "ATM SURCHARGE REBATE", replace: "ATM Fee Rebate" },
        { search: "USAA CREDIT CARD PAYMENT", replace: "USAA Credit Card Payment" }
    ]
}

/*
module.exports = {
    searches: [
        // { "search": "your dekalb", "replace": "Dekalb Farmers Market"},
        { "search": "@colony square", "replace": "Colony Square", "category": "ATM/Cash Withdrawals"},
        { "search": "reagin optometric", "replace": "Reagin Optometric Group"},
        // { "search": "wrecking bar", "replace": "Wrecking Bar"},
        // { "search": "hop city", "replace": "Hop City", "category": "Alcohol"},
        { "search": "gordon biersch", "replace": "Gordon Biersch"},
        // { "search": "wholefds", "replace": "Whole Foods"},
        // { "search": "uber tech", "replace": "Uber"},
        // { "search": "uber                     ", "replace": "Uber" },
        // { "search": "hudson grille", "replace": "Hudson Grille"},
        { "search": "miso izakaya", "replace": "Miso Izakaya", "category": "Restaurants/Dining"},
        // { "search": "lola oslo", "replace": "Lola Oslo"},
        { "search": "*t-mobile", "replace": "T-Mobile", "category": "Wireless Service"},
        // { "search": "savi urban", "replace": "Savi Market"},
        // { "search": "savi provisions", "replace": "Savi Market"},
        { "search": "hyatt atlanta", "replace": "Hyatt Atlanta", "category": "Restaurants/Dining"},
        // { "search": "home depot", "replace": "Home Depot"},
        // { "search": "netflix.com", "replace": "Netflix.com"},
        // { "search": "cafe agora", "replace": "Cafe Agora", "category": "Restaurants/Dining"},
        { "search": "sotto sotto", "replace": "Sotto Sotto", "category": "Restaurants/Dining"},
        // { "search": "kroger", "replace": "Kroger"},
        // { "search": "target", "replace": "Target"},
        { "search": "the spence", "replace": "The Spence", "category": "Restaurants/Dining"},
        { "search": "kale me", "replace": "Kale Me Crazy"},
        { "search": "bocca lupo", "replace": "Bocca Lupo"},
        // { "search": "newk's", "replace": "Newk's Midtown"},
        // { "search": "chevron", "replace": "Chevron"},
        // { "search": "petco", "replace": "Petco"},
        // { "search": "amazon.com", "replace": "Amazon.com"},
        // { "search": "amazon mktplace", "replace": "Amazon.com"},
        // { "search": "walgreens", "replace": "Walgreens"},
        // { "search": "amazon services-kindle", "replace": "Amazon.com Kindle"},
        { "search": "atl airport n hrly", "replace": "ATL Airport Parking"},
        // { "search": "banana republic", "replace": "Banana Republic" },
        { "search": "bp memorial", "replace": "BP Memorial" },
        // { "search": "fritti", "replace": "Fritti" },
        { "search": "pottery barn", "replace": "Pottery Barn" },
        { "search": "the porter", "replace": "The Porter" },
        { "search": "foreign tran", "replace": "Foreign Transaction Fee" },
        { "search": "jp boden", "replace": "Boden" },
        // { "search": "grindhouse", "replace": "Grindhouse" },
        // { "search": "barcelona atlanta", "replace": "Barcelona Wine Bar" },
        // { "search": "empire state", "replace": "Empire State South" },
        { "search": "intown animal", "replace": "Intown Animal Hospital" },
        { "search": "the cook's ware", "replace": "The Cook's Warehouse" },
        { "search": "la fonda latina", "replace": "La Fonda" },
        { "search": "shell oil", "replace": "Shell Oil" },
        { "search": "hotter comfort", "replace": "Hotter Comfort" },
        { "search": "usaa.com pmt", "replace": "USAA.COM Card Payment" },
        { "search": "usaa credit card payment", "replace": "USAA.COM Card Payment" },
        { "search": "marta atlanta", "replace": "MARTA" },
        { "search": "parking-piedmont", "replace": "Piedmont Hospital Parking" },
        { "search": "jimmy johns", "replace": "Jimmy Johns" },
        { "search": "delta air", "replace": "Delta Air" },
        { "search": "bruce a edelstein", "replace": "Edelstein DDS" },
        { "search": "global imports", "replace": "Global Imports MINI" },
        { "search": "bantam", "replace": "Bantam & Biddy", "category": "Restaurants/Dining" },
        { "search": "south city", "replace": "South City Kitchen", "category": "Restaurants/Dining" },
        { "search": "one eared stag", "replace": "One Eared Stag" },
        { "search": "joe's on juniper", "replace": "Joe's on Juniper" },
        { "search": "bed bath", "replace": "Bed Bath & Beyond" },
        { "search": "atlanta botanical garden", "replace": "Atlanta Botanical Garden", "category": "Wellbeing" },
        { "search": "lure    ", "replace": "Lure Restaurant" },
        { "search": "craft izakaya", "replace": "Craft Izakaya" },
        // { "search": "lowes", "replace": "Lowes" },
        { "search": "west elm e-commerce", "replace": "West Elm online" },
        { "search": "tap                      atlanta", "replace": "Tap"},
        { "search": "aaa park piedmont", "replace": "Piedmont Hospital Parking", "category": "Parking"},
        { "search": "mf sushi", "replace": "MF Sushi"},
        // { "search": "fred's yalla", "replace": "Yalla", "category": "Restaurants/Dining"},
        // { "search": "bar taco inman", "replace": "Bar Taco"},
        // { "search": "homedepot.com", "replace": "HomeDepot.com"},
        { "search": "mf sushi", "replace": "MF Sushi"},
        { "search": "ri ra irish", "replace": "Ri Ra Irish Pub"},
        { "search": "1010 washington wine", "replace": "1010 Washington Wine", "category": "Alcohol"},
        { "search": "the cockentrice", "replace": "The Cockentrice", "category": "Restaurants/Dining"},
        { "search": "front page news", "replace": "Front Page News"},
        { "search": "benchmark physical", "replace": "Benchmark PT", "category": "Healthcare/Medical"},
        // { "search": "google *project fi", "replace": "Google Fi", "category": "Wireless Service"},
        { "search": "qt xx", "replace": "QT", "category": "Gasoline/Fuel"},
        { "search": "ecco                     atlanta      ga", "replace": "Ecco Restaurant", "category": "Restaurants/Dining" },
        { "search": "sweet hut", "replace": "Sweet Hut", "category": "Restaurants/Dining" },
        { "search": "caffe gio", "replace": "Caffe Gio" },
        { "search": "gio's chicken", "replace": "Gio's Chicken" },
        { "search": "zappos", "replace": "Zappos" },
        { "search": "lanier parking", "replace": "Lanier Parking" },
        { "search": "bezoria", "replace": "Bezoria" },
        { "search": "sun in my belly", "replace": "Sun in My Belly", "category": "Restaurants/Dining" },
        { "search": "laz parking", "replace": "LAZ Parking" },
        { "search": "gunshow", "replace": "Gunshow" },
        { "search": "publix", "replace": "Publix" },
        { "search": "racetrac", "replace": "Racetrac", "category": "Gasoline/Fuel" },
        { "search": "madewell", "replace": "Madewell", "category": "Clothing/Shoes" },
        { "search": "grand champion bbq", "replace": "Grand Champion BBQ", "category": "Restaurants/Dining" },
        { "search": "cafe intermezzo", "replace": "Cafe Intermezzo", "category": "Restaurants/Dining" },
        { "search": "cvs/pharmacy", "replace": "CVS Pharmacy" },
        { "search": "the luminary", "replace": "The Luminary", "category": "Restaurants/Dining" },
        { "search": "j crew", "replace": "J Crew" },
        { "search": "inman dry goods", "replace": "Inman Dry Goods", "category": "Clothing/Shoes" },
        { "search": "williams-sonoma", "replace": "Williams-Sonoma", "category": "General Merchandise"},
        { "search": "williams sonoma", "replace": "Williams-Sonoma", "category": "General Merchandise"},
        { "search": "piedmont healthcare", "replace": "Piedmont Healthcare" },
        { "search": "containerstore", "replace": "Container Store" },
        { "search": "macy's east", "replace": "Macy's" },
        { "search": "sherwin williams", "replace": "Sherwin Williams" },
        { "search": "superica", "replace": "Superica", "category": "Restaurants/Dining" },
        // { "search": "huge  llc", "replace": "Huge Salary", "category": "Salary" },
        // { "search": "m arthur gensl", "replace": "Gensler Salary", "category": "Salary" },
        { "search": "green's package", "replace": "Green's", "category": "Alcohol" },
        // { "search": "citimortgage", "replace": "Citimortgage", "category": "Mortgages" },
        // { "search": "georgia nat gas", "replace": "Georgia Natural Gas", "category": "Utilities-gas" },
        // { "search": "georgia power", "replace": "Georgia Power", "category": "Utilities-electricity" },
        { "search": "USAA P", "replace": "USAA Insurance", "category": "Insurance" },
        // { "search": "Comcast", "replace": "Comcast", "category": "Cable/Satellite Services" },
        { "search": "USAA.COM PAYMNT", "replace": "USAA Credit Card Payment", "category": "Credit Card Payment" }
        ]
}
*/
